# -*- coding: utf-8 -*-
"""Text2Img.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bjbSP3dTHkVrJOXfiY1DOtzUtApH7rGm
"""

!pip install diffusers transformers torch accelerate

from diffusers import StableDiffusionPipeline
import torch

# Load the Stable Diffusion model
model_id = "CompVis/stable-diffusion-v1-4"  # Pre-trained Stable Diffusion model
pipe = StableDiffusionPipeline.from_pretrained(model_id, torch_dtype=torch.float16)

# Move the model to GPU if available
device = "cuda" if torch.cuda.is_available() else "cpu"
pipe = pipe.to(device)

# Define your text prompt
prompt = "  A 28-year-old Indian man with long hair, small moustache and a small beard, laughing happily near a river. He is wearing a white t-shirt and blue jeans. His physique is normal weight with an average build. The background shows a natural riverside setting, bright and relaxed atmosphere."

# Generate nerate the image
with torch.autocast("cuda"):  # Use autocast for mixed precision (faster on GPU)
    image = pipe(prompt).images[0]

# Save the image
image.save("Man_image.png")
print("Image saved as Man_image.png")